### PR TITLE
Make JSON schemas enter Object and Variant fields.

### PR DESCRIPTION
**Pull request by jamadden**

### CODE REVIEW

**Review by jzuech3 — APPROVED** [review]
LGTM!

**Comment by jamadden** [comment]
OK, cool. 

Just be aware that we're traversing through a lot of things we didn't in the past. That means the schemas will get bigger, and I can't help but wonder if there may be some chance of disclosing data we don't actually expect to (though I haven't been able to come up with a specific scenario). It may be necessary to define the `TAG_HIDDEN_IN_UI` more often...in fact, I think we should probably query that field before we output `key_type` and `value_type` or the fields of a variant (right now it's only queried for the top level). Thoughts?

**Comment by jzuech3** [comment]
I think we do need to worry about the schemas getting bigger, but I believe it is necessary to give accurate info on the required types of underling sequence fields. 

Agreed on making sure we also check hidden within variant. Do we need to make sure `post_process_field` is called in variant as well?

**Comment by jamadden** [comment]
> Agreed on making sure we also check hidden within variant. Do we need to make sure `post_process_field` is called in variant as well?

I have no idea what it's used for (there's no implementation, docstring, or testing of it here), so since it is currently only called for top-level fields, my instinct would be to say "no, don't start suddenly calling it for nested fields."

**Comment by jzuech3** [comment]
I'm not sure of the intended use-case either; so we can probably ignore it for now. Yesterday, I did override `post_process_field` to get the title/description defs in for a client.

This PR looks good to me.

**Comment by jamadden** [comment]
Thanks!

**Pull request merged**
