### PR TITLE
Add support for Python 3.6 and Fix #11

### LINKED ISSUE #11: SchemaConfigured try to set defaults for readonly fields (nti.schema-1.1.3)
in SchemaConfigured mixin class 

The following code is executed
```python
 for f, fields in _iteritems(schema):
          if not hasattr(self, f):
              setattr(self, f, fields.default)
```
We are getting a "AttributeError: can't set attribute" because it tries to set up a default to a readonly field
```python
class IGradeBookEntry(IContainer,IContained):

    DueDate = Date(title="The date on which the assignment is due", 
                   required=False,
                   readonly=True)

@interface.implementer(IGradeBookEntry, IAttributeAnnotatable)
class GradeBookEntry(SchemaConfigured,
					 CheckingLastModifiedBTreeContainer,
					 Contained):
	createDirectFieldProperties(IGradeBookEntry)

ge  = GradeBookEntry()
```

Carlos

### PR DESCRIPTION
**Pull request by jamadden**
Also remove use of ``unicode_literals`` throughout the code base.

### CODE REVIEW

**Comment by jamadden** [comment]
Ping @papachoco

**Comment by papachoco** [comment]
Looks good

**Comment by jamadden** [comment]
Would you like to use the official "Approve" button? I crave that green checkmark.

**Review by papachoco — APPROVED** [review]
Look good ..

**Comment by jamadden** [comment]
Thank you! 1.2.0 is on PyPI.

**Pull request merged**
